### ISSUE TITLE
Fix the github social media icon

### ISSUE THREAD

**Issue by yashrsharma44** [yashrsharma44/yashrsharma44.github.io#3]
Here the social media logo doesn't turn up - 
![image](https://user-images.githubusercontent.com/31438680/96986299-14bd3800-153f-11eb-9065-46074dda0253.png)

**Comment by georgioupanayiotis** [comment]
Hello @yashrsharma44 can you assign me this ticket?

**Comment by yashrsharma44** [comment]
Sure you can have a try!

**Comment by georgioupanayiotis** [comment]
@yashrsharma44  can you assign me this ticket ?
<img width="1338" alt="Screenshot 2020-10-23 at 10 23 53" src="https://user-images.githubusercontent.com/1752156/96986729-f264f380-1519-11eb-9a3c-61ef4ac98925.png">

**Comment by georgioupanayiotis** [comment]
Done created the PR https://github.com/yashrsharma44/yashrsharma44.github.io/pull/9
